version: 2
updates:
- package-ecosystem: docker
  directory: "/python-3.7"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - kriberg
- package-ecosystem: docker
  directory: "/python-3.6"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - kriberg
- package-ecosystem: docker
  directory: "/python-3.8"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - kriberg
