version: 1
update_configs:
  # Keep Dockerfile up to date
  - package_manager: "docker"
    directory: "python-3.8/"
    update_schedule: "daily"
    default_reviewers:
      - "kriberg"
  - package_manager: "docker"
    directory: "python-3.7/"
    update_schedule: "daily"
    default_reviewers:
      - "kriberg"
  - package_manager: "docker"
    directory: "python-3.6/"
    update_schedule: "daily"
    default_reviewers:
      - "kriberg"
